---
title: "Yelp Connections"
author: "Jeremy Sellars"
date: "November 6, 2015"
output: html_document
---

# Process data

```{r fns, cache=TRUE, echo=FALSE}
read_json_data <-
  function (d) stream_in(file(paste0("yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_", d, ".json")))

adorn <- function(df, label) {
  df[,"Type"]<-rep(label, each=nrow(df))
}

```

## Combine Users and Businesses - these are our entities

```{r entities, cache=TRUE, echo=FALSE}
business <- read_json_data("business")
business <- business[,c("business_id","name")]
business$LABEL<-rep("business", each=nrow(business))
names(business) <- c("ID","name:string","LABEL")

write.csv(business, file = "business.csv", row.names=FALSE)

user <- read_json_data("user")[,c("user_id","name")]
user$LABEL<-rep("user", each=nrow(user))
names(user) <- c("ID","name:string","LABEL")
write.csv(user, file = "user.csv", row.names=FALSE)

entity <- c(business$business_id, user$user_id)
length(entity)
```

## Get edges 

```{r relationships, cache=TRUE, echo=FALSE}
tip_edges <- read_json_data("tip")[,c("user_id","business_id")]
tip_edges$Type<-rep("tip_edges", each=nrow(tip_edges))
review_edges <- read_json_data("review")[,c("user_id","business_id")]
review_edges$Type<-rep("review_edges", each=nrow(review_edges))
#friend_edges <- user[,"friends"]
#friend_edges$Type<-rep("friend_edges", each=nrow(friend_edges))
undirected_edges <- rbind(tip_edges, review_edges)
#edges <- rbind(undirected_edges[,c("user_id","business_id","Type")],
#               undirected_edges[,c("business_id","user_id","Type")])
edges <- undirected_edges
names(edges) <- c("START_ID","END_ID","TYPE")
write.csv(edges, file = "edges.csv", row.names=FALSE)
```

## Create an adjacency matrix

```{r adj}
entity_count <- length(entity)
adj_matrix <- filebacked.big.matrix(nrow = entity_count, ncol = entity_count, backingpath="c:\\temp\\", backingfile = "rmatrix", descriptorfile = "rmatrix.descriptor", type="integer", init=256, dimnames=list(names(entity),names(entity)))
```


