---
title: "Friendly Friends on Yelp"
author: "Jeremy Sellars"
date: "November 13, 2015"
output: html_document
---

```{r fns, cache=TRUE, echo=FALSE}
library(jsonlite)
library(ggplot2)
setwd("/code/jeremy.sellars/coursera/dsscapstone")
read_json_data <-
  function (d, prefix="yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_") stream_in(file(paste0(prefix, d, ".json")))
```

```{r fc, cache=TRUE, echo=FALSE}
fc_file <- "friend_count.rds"
if (!file.exists(fc_file)){
  #user <- read_json_data("user")
  #user <- user[,c("user_id","name","friends")]
  user <- read_json_data("user_friend_counts", prefix="friend-count/")
  user$friend_count <- unlist(lapply(user$"friend-counts", length))
  friend_count <- user[,c("user_id","name","friend_count","friend-counts")]
  saveRDS(friend_count, fc_file)
} else {
  friend_count <- readRDS(fc_file)
}
friend_count$mean_ct <- unlist(lapply(friend_count$"friend-counts", mean))
friend_count$median_ct <- unlist(lapply(friend_count$"friend-counts", median))
friend_count$sd_ct <- unlist(lapply(friend_count$"friend-counts", sd))
friend_count$friend_class <- ifelse(
  friend_count$friend_count <= 1,
  0,
  as.integer((friend_count$friend_count - friend_count$mean_ct)/friend_count$sd_ct))
friend_count$friend_class <- ifelse(
  friend_count$friend_class < -2,
  -2,
  ifelse(
    friend_count$friend_class > 2,
    2,
    friend_count$friend_class))
summary(friend_count$friend_class)
fc <- as.data.frame(friend_count[,c("friend_count", "mean_ct", "median_ct", "sd_ct", "friend_class")])
#fc$friend_class <- as.integer(log10(fc$friend_count))
```


[comment]: # (R2 - required title)
# Friendly Friends on Yelp

[comment]: # (R2 - required section)
## Introduction

[comment]: # (R2 - required section)
## Methods

[comment]: # (R2 - required section)
## Results

```{r results, echo=F}
summary(fc)
  ggplot(fc, aes(x=fc$friend_count)) + 
  geom_histogram() + facet_grid(. ~ friend_class, margins=TRUE)
```

[comment]: # (R2 - required section)
## Discussion

